// export const Questions = [
//     {
//       ques: "1) Which of the following is used in React.js to increase performance ?",
//       optionA: "A)-Virtual dom",
//       optionB: "B)-Real dom",
//       optionC: "C)-Both A and B",
//       optionD: "D)-None of the above",
//       ans: "optionA",
//     },
//     {
//       ques: "2)What is ReactJS?",
//       optionA: "A)-Server side framework",
//       optionB: "B)-user-interface framework",
//       optionC: "C)-Both A and B",
//       optionD: "D)-None of the above",
//       ans: "optionB",
//     },
//     {
//       ques: "3)Identify the one which is used to pass data to components from outside?",
//       optionA: "A)-Render with arguments",
//       optionB: "B)-setState",
//       optionC: "C)-PropTypes",
//       optionD: "D)-Props",
//       ans: "optionD",
//     },
//     {
//       ques: " 4)In which language is React.js written?",
//       optionA: "A)-Python",
//       optionB: "B)-JavaScript",
//       optionC: "C)-Java",
//       optionD: "D)-PHP",
//       ans: "optionB",
//     },
//     {
//       ques: " 5)What is Babel?",
//       optionA: "A)-JavaScript Compiler",
//       optionB: "B)-JavaScript Interpreter ",
//       optionC: "C)-javaScript Transpiler",
//       optionD: "D)-None of the above",
//       ans: "optionA",
//     },
//     {
//       ques: " 6)JSX stands for __________?",
//       optionA: "A)-JavaScript XML",
//       optionB: "B)-JSON XML",
//       optionC: "C)-JSON",
//       optionD: "D)-JavaScript and AngularJS",
//       ans: "optionA",
//     },
//     {
//       ques: " 7)State whether true or false:  Props are methods into other components?",
//       optionA: "A)-True",
//       optionB: "B)-False",
//       ans: "optionA",
//     },
//     {
//       ques: " 8)Using which of the following command can prevent default behaviour at in react?",
//       optionA: "A)-preventDefault()",
//       optionB: "B)-avoidDefault()",
//       optionC: "C)-revokeDefault()",
//       optionD: "D)-None of the above",
//       ans: "optionA",
//     },
//     {
//       ques: " 9)Identify the smallest building block of React.JS?",
//       optionA: "A)-Props",
//       optionB: "B)-Elements",
//       optionC: "C)-Components",
//       optionD: "D)-None of the above",
//       ans: "optionC",
//     },
//     {
//       ques: "10)What is ReactJS mainly used for building?",
//       optionA: "A)-DataBase",
//       optionB: "B)-Connectivity",
//       optionC: "C)-User-Interface",
//       optionD: "D)-Design Platform",
//       ans: "optionC",
//     },
//   ];
  